[[mUCAnnouncement]]
= Announcement
:author: Andrzej Wójcik
:version: v2.0 October 2017. Reformatted for v8.0.0.

:toc:
:numbered:
:website: http://tigase.net

== Major changes
Tigase MUC component has undergone a few major changes to our code and structure. To continue to use Tigase MUC component, a few changes may be needed to be made to your systems. Please see them below:

=== Database schema changes
We decided to improve performance of MUC repository storage and to do so we needed to change database schema of MUC component.
Additionally we decided to no longer use _in-code_ database upgrade to update database schema of MUC component and rather provide separate schema files for every supported database.

To continue usage of new versions of MUC component it is required to manually load new component database schema, see <<Preparation of database>> section for informations about that.

Moreover we no longer store rooms list and configurations inside `UserRepository` of default Tigase XMPP Server database. Instead we use separate tables which are part of new schema.
Due to that it is required to execute converter which will move room configurations from `UserRepository` to new tables.
It needs to be executed *AFTER* new database schema is loaded to database.

NOTE: If you used separate database to store messages history we strongly suggest to use same database for new schema and storage of rooms configurations as well. In other case message history will not be moved to new schema.

In `database` directory of installation package there is a `muc-db-migrate` utility which takes 2 parameters:

-in 'jdbc_uri_to_user_repository'::
To set JDBC URI of UserRepository
-out 'jdbc_uri_to_muc_database'::
To set JDBC URI of database with loaded database schema.

TIP: Both JDBC uri's may be the same.

WARNING: During this opeartion it removes room configurations from old storage.

==== Examples
UNIX / Linux / OSX::
----
database/muc-db-migrate.sh -in 'jdbc:mysql://localhost/database1' -out 'jdbc:mysql://localhost/database2'
----

Windows::
----
database/muc-db-migrate.cmd -in 'jdbc:mysql://localhost/database1' -out 'jdbc:mysql://localhost/database2'
----

=== Support for MAM
In this version we added support for http://xmpp.org/extensions/xep-0313.html:[XEP-0313: Message Archive Management] protocol which allows any MAM compatible XMPP client with MUC support to retrieve room chat history using MAM and more advanced queries than retrieval of last X messages or messages since particular date supported by MUC
